Removes coordination complexes compounds
RECETOX/galaxytools pull request #441
Opened 2023-11-22 09:19 UTC by wverastegui

The tool removes only coordination complexes compounds from a list of smiles. The input files can be csv, InChI and SMILEs formats. The tool return same input formats as output file formats.

Linked issue:  https://github.com/RECETOX/galaxytools/issues/430

2023-11-22 10:08 UTC, hechth requested changes
Couple of changes are needed before this can be merged - please see the comments and ask if anything is unclear :)

2023-11-22 10:08 UTC, hechth commented on tools/rem_complex/rem_complex.py
> +                    f.write(mol.write(file_extension))
There are many things in this section which could be refactored, but mainly the loops could be simplified. If your entire function is in an if clause, you're doing something wrong. Either invert the check (as seen in the example above) or only call the function if the condition is true.

2023-11-22 11:39 UTC, wverastegui commented on tools/rem_complex/rem_complex.py
> +openbabel.obErrorLog.StopLogging()
I could not find documentation about this. Althought, the change allows to enable/disable the log. Not sure how useful it this. By the way, messages only appears for InChI format.

2023-11-22 12:12 UTC, wverastegui commented on tools/rem_complex/macros.xml
> +    <token name="@TOOL_VERSION@">6.6.1</token>
I used other tool as template. Is it accurate 1.0.0?, since it is created for the first time.

2023-11-22 12:50 UTC, wverastegui commented on tools/rem_complex/test-data/input.csv
Reduced ([92f7cfa](https://github.com/RECETOX/galaxytools/pull/441/commits/92f7cfa8887d780011b4a7ac2ec6b6518c970c2e))

2023-11-22 14:14 UTC, wverastegui commented on tools/rem_complex/rem_complex.py
> +def filter_complex_molecules(file_name, output_file_name, input_format):
Added ([1404cde](https://github.com/RECETOX/galaxytools/pull/441/commits/1404cde0ec0546a5a955b05812d12ca98491328c))

2023-11-27 08:09 UTC, hechth reviewed
Do the testdata in inchi and smiles formats represent the same compounds?

2023-11-27 08:09 UTC, hechth commented on tools/rem_complex/rem_complex.xml
> +    <description>Remove molecular coordination complexes </description>
```suggestion
<tool id="rem_complex" name="Remove coordination complexes" version="@TOOL_VERSION@+galaxy1"  profile="21.09">
    <description>Remove molecular coordination complexes from a list of structure representations</description>
```

2023-11-27 08:21 UTC, hechth approved these changes

2023-11-27 08:55 UTC, merged